[project]
site_name = "Lejonet HTR"
site_url = "https://ai-riksarkivet.github.io/lejonet"
site_description = "Collaborative handwritten text recognition for historical documents"
site_author = "AI-Riksarkivet"
copyright = "&copy; 2026 AI-Riksarkivet"
docs_dir = "docs"
site_dir = "site"

[project.theme]
variant = "modern"
