apiVersion: v2
name: ra-atr
description: Svelte 5 frontend for handwritten text recognition with in-browser ONNX Runtime WASM inference
type: application
version: 0.1.0
appVersion: "v0.1.0"
home: https://github.com/AI-Riksarkivet/ra-atr
sources:
  - https://github.com/AI-Riksarkivet/ra-atr